module.exports = {
    'US_CHG': {
        "code": 'selection-btn-A2415SD4I3NE6W-ATVPDKIKX0DER-announce',
        "merchant_id": "A2415SD4I3NE6W",
        "marketplace_id": 'ATVPDKIKX0DER',
        "marketplace": 'US',
        "secret_key": "xNuEXx0FWMO96BMkADfUdICtmjb98jqSBbyUT0+O",
        "access_key": "AKIAI2NAVBW5PZCAUZLA",
        "mws_auth_token": "amzn.mws.2aae44b9-7834-e426-ee82-3bbaf638cf1d",
        "country": 'USA',
        "company": "CHG",
        "url": "https://sellercentral.amazon.com",
    },
    'CA_CHG': {
        "code": 'selection-btn-A2415SD4I3NE6W-ATVPDKIKX0DER-announce',
        "merchant_id": "A2415SD4I3NE6W",
        "marketplace_id": 'A2EUQ1WTGCTBG2',
        "marketplace": 'CA',
        "secret_key": "xNuEXx0FWMO96BMkADfUdICtmjb98jqSBbyUT0+O",
        "access_key": "AKIAI2NAVBW5PZCAUZLA",
        "mws_auth_token": "amzn.mws.2aae44b9-7834-e426-ee82-3bbaf638cf1d",
        "country": 'CAN',
        "company": "CHG",
        "url": "https://sellercentral.amazon.com",
    },
    'US_MPH': {
        "code": 'selection-btn-A3SFF90I3AI4GN-ATVPDKIKX0DER-announce',
        "merchant_id": "A3SFF90I3AI4GN",
        "marketplace_id": 'ATVPDKIKX0DER',
        "marketplace": 'US',
        "secret_key": "xNuEXx0FWMO96BMkADfUdICtmjb98jqSBbyUT0+O",
        "access_key": "AKIAI2NAVBW5PZCAUZLA",
        "mws_auth_token": "amzn.mws.8aaf4de1-e3b2-37d9-1a0d-98f1aeed3c76",
        "country": 'USA',
        "company": "MPH",
        "url": "https://sellercentral.amazon.com"
    },
    'CA_MPH': {
        "code": 'selection-btn-A3SFF90I3AI4GN-ATVPDKIKX0DER-announce',
        "merchant_id": "A3SFF90I3AI4GN",
        "marketplace_id": 'A2EUQ1WTGCTBG2',
        "marketplace": 'CA',
        "secret_key": "xNuEXx0FWMO96BMkADfUdICtmjb98jqSBbyUT0+O",
        "access_key": "AKIAI2NAVBW5PZCAUZLA",
        "mws_auth_token": "amzn.mws.8aaf4de1-e3b2-37d9-1a0d-98f1aeed3c76",
        "country": 'CAN',
        "company": "MPH",
        "url": "https://sellercentral.amazon.com"
    }
}